<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JSP - Hello World</title>
</head>
<body>
<h1>Generated by: JSP</h1>
<%!
    int x = 0;  /* This goes into the servlet class */
%>
<%
    x++;        /* This code goes into the doGet() method or service() method */
%>
<h1>
    <%-- resp.getWriter.println(x) --%>
    <%= x %>
</h1>
</body>
</html>