package lk.ijse.dep11.web;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.time.LocalDateTime;

//@WebServlet("/hello")
public class HelloServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setContentType("text/html");
        resp.getWriter().println("<!DOCTYPE html>\n" +
                "<html>\n" +
                "<head>\n" +
                "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n" +
                "    <title>JSP - Hello World</title>\n" +
                "</head>\n" +
                "<body>");

        resp.getWriter().println("<h1>Generated By: Servlet</h1>");
        for (int i = 0; i < 5; i++) {
            resp.getWriter().printf("<h1>%s</h1>", "Hello World! " + LocalDateTime.now());
        }
        resp.getWriter().println("</body></html>");
    }
}
